SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

UNIT_LENGTH = 4
UNIT_DISTANCE = 1

ARRAY_LENGTH = SCREEN_WIDTH // (UNIT_LENGTH + UNIT_DISTANCE)
UNIT_Y_SCALE = SCREEN_HEIGHT // ARRAY_LENGTH * 9 // 10
FPS = ARRAY_LENGTH

MARGIN_X = 0  # SCREEN_WIDTH * 1 / 10
MARGIN_Y = SCREEN_HEIGHT * 9 / 10

BACKGROUND_COLOR = "#2B2B2B"
UNIT_COLOR = 'green'
